version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  test-python-app:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          app-dir: ~/project/flask-api
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          command: |
            pytest -v
          name: Test

workflows:
  test:
    jobs:
      - test-python-app